### ISSUE TITLE
[Feature Request] Option to Disable Prompt Reordering

### ISSUE THREAD

**Issue by MondayMonkey1** [KohakuBlueleaf/z-a1111-sd-webui-dtg#11]
Hello,

I often use Forge Attention Couple, which requires separate prompts for each person or character. Currently, the automatic prompt reordering can interfere with this process.
Could you please consider adding an option to disable the feature? Keeping the prompts in their original order would be very helpful.

Thanks.

**Comment by KohakuBlueleaf** [comment]
Does that have any syntax to indicate seperate prompts?
it is impossible to "don't do any prompt reordering".
Especially for your requirements, you still need to indicate where you want to put the new tags.

**Comment by KohakuBlueleaf** [comment]
I will add a feature to ignore all the post-processing formatting but it can only append newly added tags in the end of your prompt.

But I think what you want is actually "apply DTG to different part seperatedly"

**Comment by KohakuBlueleaf** [comment]
No formatting feature added.
