### ISSUE TITLE
[Bug]: Transformer model failed to load if select gguf first but failed to load gguf model

### ISSUE THREAD

**Issue by ananosleep** [KohakuBlueleaf/z-a1111-sd-webui-dtg#12]
select model: DanTagGen-gamma_ggml-model-f16.gguf
log:
![image](https://github.com/KohakuBlueleaf/z-a1111-sd-webui-dtg/assets/126318157/db71066c-1e92-40ed-a862-eb2fc260475b)

The repo's name should be `KBlueLeaf/DanTagGen-gamma` instead of `DanTagGen-gamma`

**Comment by KohakuBlueleaf** [comment]
It looks more like you have some issue to connect to HuggingFace.

Have checked. it can load the model correctly

**Comment by ananosleep** [comment]
I have checked my Internet and I'm sure the issue is not related to network.
By the way, according to the console log, the url I highlighted is surely wrong.

The way to reproduce this bug is to **select gguf model** and trigger **llama-cpp-python load failed**. 
**Only in this way** transformers would get the wrong repo name.

**Select transformers model directly** works correctly.
