### ISSUE TITLE
Can't see a DanTagGen-delta-rev2 in the model list

### ISSUE THREAD

**Issue by rltgjqmcpgjadyd** [KohakuBlueleaf/z-a1111-sd-webui-dtg#13]
![image](https://github.com/KohakuBlueleaf/z-a1111-sd-webui-dtg/assets/115572150/9d77408c-38fc-4b12-8caa-e929ef8e95d2)

Only rev2 is missing

**Comment by KohakuBlueleaf** [comment]
update the "tipo-kgen" lib in your environment.
