### ISSUE TITLE
sometimes the tag upsampler changes "BREAK" to "(BREAK:-1), reducing image quality.

### ISSUE THREAD

**Issue by Hugs288** [KohakuBlueleaf/z-a1111-sd-webui-dtg#4]
maybe could be fixed with changing some settings? im not sure honestly

**Comment by KohakuBlueleaf** [comment]
I need to dig into whole sd-webui prompt processing system to ensure I can get something after all prompt parsing...
Still investigating

**Comment by KohakuBlueleaf** [comment]
Fixed
