### ISSUE TITLE
 AttributeError: function 'llama_mmap_supported' not found

### ISSUE THREAD

**Issue by Mystos007** [KohakuBlueleaf/z-a1111-sd-webui-dtg#7]
I get the following error:

```
2024-04-17 21:53:16|[TOPI-KGen]-WARNING: Llama-cpp-python cannot be imported
*** Error loading script: dtg.py
    Traceback (most recent call last):
      File "C:\GitStuff\stable-diffusion-webui\modules\scripts.py", line 508, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "C:\GitStuff\stable-diffusion-webui\modules\script_loading.py", line 14, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "C:\GitStuff\stable-diffusion-webui\extensions\z-a1111-sd-webui-dtg\scripts\dtg.py", line 24, in <module>
        from kgen.generate import tag_gen
      File "C:\GitStuff\stable-diffusion-webui\venv\lib\site-packages\kgen\generate.py", line 9, in <module>
        from llama_cpp import Llama
      File "C:\GitStuff\stable-diffusion-webui\venv\lib\site-packages\llama_cpp\__init__.py", line 1, in <module>
        from .llama_cpp import *
      File "C:\GitStuff\stable-diffusion-webui\venv\lib\site-packages\llama_cpp\llama_cpp.py", line 715, in <module>
        _lib.llama_mmap_supported.argtypes = []
      File "C:\Python310\lib\ctypes\__init__.py", line 387, in __getattr__
        func = self.__getitem__(name)
      File "C:\Python310\lib\ctypes\__init__.py", line 392, in __getitem__
        func = self._FuncPtr((name_or_ordinal, self))
    AttributeError: function 'llama_mmap_supported' not found
```
	
And the "accordion" menu for DanTagGen doesn't show.

**Comment by Jaystarpoi** [comment]
Same.

[TIPO-KGen]-|20:17:30|-WARNING: Llama-cpp-python cannot be imported
*** Error loading script: dtg.py
    Traceback (most recent call last):
      File "G:\sd-webui-aki-v4.2\python\lib\site-packages\llama_cpp\llama_cpp.py", line 74, in _load_shared_library
        return ctypes.CDLL(str(_lib_path), **cdll_args)
      File "G:\sd-webui-aki-v4.2\python\lib\ctypes\__init__.py", line 374, in __init__
        self._handle = _dlopen(self._name, mode)
    FileNotFoundError: Could not find module 'G:\sd-webui-aki-v4.2\python\lib\site-packages\llama_cpp\llama.dll' (or one of its dependencies). Try using the full path with constructor syntax.

    During handling of the above exception, another exception occurred:
    Traceback (most recent call last):
      File "G:\sd-webui-aki-v4.2\modules\scripts.py", line 508, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "G:\sd-webui-aki-v4.2\modules\script_loading.py", line 14, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "G:\sd-webui-aki-v4.2\extensions\z-a1111-sd-webui-dtg\scripts\dtg.py", line 24, in <module>
        from kgen.generate import tag_gen
      File "G:\sd-webui-aki-v4.2\python\lib\site-packages\kgen\generate.py", line 8, in <module>
        from llama_cpp import Llama
      File "G:\sd-webui-aki-v4.2\python\lib\site-packages\llama_cpp\__init__.py", line 1, in <module>
        from .llama_cpp import *
      File "G:\sd-webui-aki-v4.2\python\lib\site-packages\llama_cpp\llama_cpp.py", line 87, in <module>
        _lib = _load_shared_library(_lib_base_name)
      File "G:\sd-webui-aki-v4.2\python\lib\site-packages\llama_cpp\llama_cpp.py", line 76, in _load_shared_library
        raise RuntimeError(f"Failed to load shared library '{_lib_path}': {e}")
    RuntimeError: Failed to load shared library 'G:\sd-webui-aki-v4.2\python\lib\site-packages\llama_cpp\llama.dll': Could not find module 'G:\sd-webui-aki-v4.2\python\lib\site-packages\llama_cpp\llama.dll' (or one of its dependencies). Try using the full path with constructor syntax.

**Comment by KohakuBlueleaf** [comment]
Try to reinstall llama-cpp

**Comment by KohakuBlueleaf** [comment]
> Same.
> 
> [TIPO-KGen]-|20:17:30|-WARNING: Llama-cpp-python cannot be imported *** Error loading script: dtg.py Traceback (most recent call last): File "G:\sd-webui-aki-v4.2\python\lib\site-packages\llama_cpp\llama_cpp.py", line 74, in _load_shared_library return ctypes.CDLL(str(_lib_path), **cdll_args) File "G:\sd-webui-aki-v4.2\python\lib\ctypes__init__.py", line 374, in **init** self._handle = _dlopen(self._name, mode) FileNotFoundError: Could not find module 'G:\sd-webui-aki-v4.2\python\lib\site-packages\llama_cpp\llama.dll' (or one of its dependencies). Try using the full path with constructor syntax.
> 
> ```
> During handling of the above exception, another exception occurred:
> Traceback (most recent call last):
>   File "G:\sd-webui-aki-v4.2\modules\scripts.py", line 508, in load_scripts
>     script_module = script_loading.load_module(scriptfile.path)
>   File "G:\sd-webui-aki-v4.2\modules\script_loading.py", line 14, in load_module
>     module_spec.loader.exec_module(module)
>   File "<frozen importlib._bootstrap_external>", line 883, in exec_module
>   File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
>   File "G:\sd-webui-aki-v4.2\extensions\z-a1111-sd-webui-dtg\scripts\dtg.py", line 24, in <module>
>     from kgen.generate import tag_gen
>   File "G:\sd-webui-aki-v4.2\python\lib\site-packages\kgen\generate.py", line 8, in <module>
>     from llama_cpp import Llama
>   File "G:\sd-webui-aki-v4.2\python\lib\site-packages\llama_cpp\__init__.py", line 1, in <module>
>     from .llama_cpp import *
>   File "G:\sd-webui-aki-v4.2\python\lib\site-packages\llama_cpp\llama_cpp.py", line 87, in <module>
>     _lib = _load_shared_library(_lib_base_name)
>   File "G:\sd-webui-aki-v4.2\python\lib\site-packages\llama_cpp\llama_cpp.py", line 76, in _load_shared_library
>     raise RuntimeError(f"Failed to load shared library '{_lib_path}': {e}")
> RuntimeError: Failed to load shared library 'G:\sd-webui-aki-v4.2\python\lib\site-packages\llama_cpp\llama.dll': Could not find module 'G:\sd-webui-aki-v4.2\python\lib\site-packages\llama_cpp\llama.dll' (or one of its dependencies). Try using the full path with constructor syntax.
> ```

Your problem is not same.

**Comment by Jaystarpoi** [comment]
> Same.
> 
> [TIPO-KGen]-|20:17:30|-WARNING: Llama-cpp-python cannot be imported *** Error loading script: dtg.py Traceback (most recent call last): File "G:\sd-webui-aki-v4.2\python\lib\site-packages\llama_cpp\llama_cpp.py", line 74, in _load_shared_library return ctypes.CDLL(str(_lib_path), **cdll_args) File "G:\sd-webui-aki-v4.2\python\lib\ctypes__init__.py", line 374, in **init** self._handle = _dlopen(self._name, mode) FileNotFoundError: Could not find module 'G:\sd-webui-aki-v4.2\python\lib\site-packages\llama_cpp\llama.dll' (or one of its dependencies). Try using the full path with constructor syntax.
> 
> ```
> During handling of the above exception, another exception occurred:
> Traceback (most recent call last):
>   File "G:\sd-webui-aki-v4.2\modules\scripts.py", line 508, in load_scripts
>     script_module = script_loading.load_module(scriptfile.path)
>   File "G:\sd-webui-aki-v4.2\modules\script_loading.py", line 14, in load_module
>     module_spec.loader.exec_module(module)
>   File "<frozen importlib._bootstrap_external>", line 883, in exec_module
>   File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
>   File "G:\sd-webui-aki-v4.2\extensions\z-a1111-sd-webui-dtg\scripts\dtg.py", line 24, in <module>
>     from kgen.generate import tag_gen
>   File "G:\sd-webui-aki-v4.2\python\lib\site-packages\kgen\generate.py", line 8, in <module>
>     from llama_cpp import Llama
>   File "G:\sd-webui-aki-v4.2\python\lib\site-packages\llama_cpp\__init__.py", line 1, in <module>
>     from .llama_cpp import *
>   File "G:\sd-webui-aki-v4.2\python\lib\site-packages\llama_cpp\llama_cpp.py", line 87, in <module>
>     _lib = _load_shared_library(_lib_base_name)
>   File "G:\sd-webui-aki-v4.2\python\lib\site-packages\llama_cpp\llama_cpp.py", line 76, in _load_shared_library
>     raise RuntimeError(f"Failed to load shared library '{_lib_path}': {e}")
> RuntimeError: Failed to load shared library 'G:\sd-webui-aki-v4.2\python\lib\site-packages\llama_cpp\llama.dll': Could not find module 'G:\sd-webui-aki-v4.2\python\lib\site-packages\llama_cpp\llama.dll' (or one of its dependencies). Try using the full path with constructor syntax.
> ```

Solved by updating llama_cpp .

**Comment by Mystos007** [comment]
I solved it by git cloning llama_cpp to a different directory, then copying to the stable-diffusion-webui\venv\Lib\site-packages folder.

**Comment by KohakuBlueleaf** [comment]
I will make the error handling more robust and add some warning about that
Will close this issue at first since is more related to the malformed environment
