### ISSUE TITLE
DTG delta and delta-rev2 not showing up in model list

### ISSUE THREAD

**Issue by Aaron-CHM** [KohakuBlueleaf/z-a1111-sd-webui-dtg#9]
Hi, I've updated to the latest version of the extension (commit ed274ff74532bda7913a25d75493c21a52cc218f) on both A1111 Webui and Forge, neither of them show DTG Delta and Delta-rev2 in the model list.
<img width="567" alt="image" src="https://github.com/KohakuBlueleaf/z-a1111-sd-webui-dtg/assets/64004039/5bcf17a6-0fdd-49c1-a1d1-58a853883cd7">

Have also downloaded the delta and delta-rev2 repositories in Forge and placed them with the same subfolder scheme as what Forge downloads: "stable-diffusion-webui-forge\models\diffusers\models--KBlueLeaf--DanTagGen-delta\snapshots\ (commit hash)", but they still do not show up in the model list. Have not attempted the same for A1111 Webui as I am unable to find the directory where DTG models are saved in A1111 Webui.
![image](https://github.com/KohakuBlueleaf/z-a1111-sd-webui-dtg/assets/64004039/8722ca3f-e848-45a0-a43f-115e507467bf)

**Comment by KohakuBlueleaf** [comment]
The "tipo-kgen" library of your environment is not latest.
Try to update them manually
